v_backbone:
  vit_base_patch16_384:
    image_size: 384
    patch_size: 16
    d_model: 768
    n_heads: 12
    n_layers: 12
    drop_path_rate: 0.1
    dropout: 0.0
    normalization: vit
    distilled: false


l_backbone:
  transformer_glove:
    d_lang: 300
    drop_path_rate: 0.0
    dropout: 0.0
    n_layers: 6


fusion_module:
  drop_path_rate: 0.1
  dropout: 0.0
  n_layers: 2
  n_up: 4

